export type Role = "ADMIN" | "PEDAGOGICAL_COORDINATOR" | "TEACHER" | "STUDENT";
export type User = { id: number; fullName: string; ra: string; email: string; role: Role; classroomId: number | null };
export type CreateUser = Pick<User, "fullName" | "ra" | "email">;
export type UserPage = { content: User[]; page: number; size: number; totalElements: number; totalPages: number };
export type UserFilters = { q?: string; page?: number; size?: number; classroomId?: number; unassigned?: boolean };
export type UserResource = "students" | "teachers" | "coordinators";
export type Classroom = { id: number; name: string; identifier: string; teacherIds: number[] };
export type CreateClassroom = Pick<Classroom, "name" | "identifier">;
export type Subject = { id: number; name: string; classroomId: number; teacherId: number };
